### ISSUE TITLE
When I try to login with webId I get an error message with no content 

### ISSUE THREAD

**Issue by mariha** [OpenHospitalityNetwork/sleepy-bike-solid#89]
I tried to login with my webId `https://solidcommunity.net/mariha` instead of logging by identity provider website (which works with no issues), and I got an error as below:

![Screenshot_20240303-171705](https://github.com/OpenHospitalityNetwork/sleepy.bike/assets/22178949/ba5248a8-0754-4142-8ef5-ba616b5faac9)

A few other people who tried this way of logging in got the same result.

**Comment by mrkvon** [comment]
Good catch!

The issue happens, because the provided URI is not a correct webId. The webId for solidcommunity.net would typically look like `https://[username].solidcommunity.net/profile/card#me`. That being said, we should provide a proper error message.

We may also consider handling such common errors even more gracefully - when the domain contains solidcommunity.net or other well-known provider, we could automatically use the correct provider, regardless whether the provided url is exactly correct.

**Comment by mariha** [comment]
According to https://solidproject.org/faqs#what-is-a-webid, any URI ([IRI](https://tools.ietf.org/html/rfc3987) to be precise, which extends URI by some added characters) can be a valid WebID, if it can be dereferenced as a [FOAF](http://xmlns.com/foaf/spec/) profile document. So a client-side format validation beyond IRI is not possible.  

I'd still add an information that "typical" WebId has a format of `https://[username].pod.provider/profile/card#me`.

Better error message - for sure. This must be a common mistake and somehow intuitive flow, because I got to know about the bug from a cyclist who stayed at my home and he said his friend got the same result when trying to login - an error with no message. Still it's possible to get:
> We didn't succeed with redirecting to the issuer. Have you provided correct webId or OIDCIssuer? Or is it down?

Detection of well-known providers - maybe... people in general find it very confusing that they are redirected somewhere else to create an account. I'd still consider hiding it behind a request that we would make to create an account with a selected pod provider or better explaining what is happening and why they are being redirected.
